
var icon_list = [
    ["angle-down", "arrow-down"],
    ["angle-left", "arrow-left"],
    ["angle-right", "arrow-right"],
    ["angle-up", "arrow-up"],
    ["arrow-back", null],
    ["caret-down", "caret-bottom"],
    ["caret-up", "caret-top"],
    ["caret-left", "caret-left"],
    ["caret-right", "caret-right"],
    ["caret", "el-icon-d-caret"],
    ["exchange-solid", null],
    ["folder", null],
    ["doc", null],
    ["key", null],
    ["linear-scale", null],
    ["lock-open", null],
    ["person", "pt-yonghu1"],
    ["print", null],
    ["view-headline", "pt-fenlei1"],
    ["view-module", "pt-fenlei"],
    ["account", "pt-daohang-yonghu"],
    ["add", null],
    ["apps", "pt-leimu"],
    ["brush", null],
    ["call-made", null],
    ["camera", null],
    ["check", "check"],
    ["close", "close", "pt-guanbi"],
    ["clouddownload", "pt-xiazai"],
    ["copy", null],
    ["create-square", "edit", "pt-tianjia"],
    ["date", "date"],
    ["delete", "delete"],
    ["download", null],
    ["edit", null],
    ["email", "pt-youjian"],
    ["explore", null],
    ["filter", null],
    ["home", "pt-shouye"],
    ["information", "information"],
    ["keyboard_voice", null],
    ["local_phone", "pt-dianhua"],
    ["lock", "pt-mima"],
    ["menu", "menu"],
    ["message", "message"],
    ["minus", "minus"],
    ["more", "more", "pt-gengduo"],
    ["notifications", null],
    ["page-empty", null],
    ["page", "document"],
    ["picture", "picture", "pt-tupian"],
    ["plus-square", "plus"],
    ["power-off", "circle-close"],
    ["power", "pt-tuichu"],
    ["publish", "pt-fabu"],
    ["refresh", "pt-shuaxin"],
    ["save", null],
    ["search", "search", "pt-sousuo"],
    ["send", null],
    ["setting", "setting", "pt-shezhi"],
    ["share", "share", "pt-fenxiang"],
    ["sharing", null],
    ["star-off", "star-off", "pt-shoucang"],
    ["star-on", "star-on"],
    ["success", "circle-check"],
    ["upload", "upload", "pt-shangchuan"],
    ["videocam", null],
    ["view", "view"],
    ["warning", "warning"],
    ["watch", "time"],
    ["zoomout", null],
    ["xls", null],
    ["ppt", null],
    ["txt", null],
    ["unknown", null],
    ["pdf", null],
    ["music", null],
    ["zip", null],
    ["view-quilt", null],
    ["approve", null],
    ["in-approve", null],
    ["history", null],

    ["people", null],
    ["accounts", null],
    ["assignment-ind", null],
    ["assignment", null],
    ["contract", null],
    ["description", null],
    ["exit-to-app", null],
    ["find-in-page", null],
    ["folder-shared", null],
    ["grant", null],
    ["organization", null],
    ["payroll", null],
    ["calculator", null],
    ["duty", null],
    ["recent-actors", null],
    ["salary", null],
    ["settings-applications", null],
    ["swap-horiz", null],
    ["wage-increase", null],

    ["sort", null],
    ["attachment", null],
    ["cloud", null],
    ["emoticon", null],
    ["place", null],
    ["scan", null],
    ["star_half", null],
    ["thumb_up", null],
    ["work", null],
    ["person_add", null],
    ["group_add", null],

    ["advance-payment", null],
    ["business-reporting", null],
    ["pause", null],
    ["general-expenses", null],
    ["image-worktable", null],
    ["job-management-worktable", null],
    ["job-worktable", null],
    ["merchants-reimbursement", null],
    ["stop", null],
    ["performance-analysis", null],
    ["rembursement", null],
    ["performance-worktable", null],
    ["travel-reimbursement", null],
    ["travel-application", null],
    ["travel-to-borrow", null],
    ["through-examination-and-approval", null],
    ["reject", null],
    ["have-to-pay", null],

    ["redo", null],
    ["signed", null],
    ["settlement-success", null],
    ["business", null],
    ["developer-board", null],
    ["library-add", null],
    ["multi-file", null],
    ["patch", null],
    ["person-cancel", null],
    ["query-template", null],
    ["restore", null],
    ["save-alt", null],
    ["supervised-user", null],
    ["UI-template-management", null],
    ["web", null],
    ["baseline-check_box", null],
    ["check_circle_outline", null],
    ["highlight_off", null],
    ["equalizer", null],
    ["receipt", null],
    ["visibility", null],
    ["extension", null],

    ["personnel-allotment", null],
    ["personnel-management", null],
    ["up", null],
    ["down", null],
    ["left", null],
    ["right", null],
    ["bottom", null],
    ["ascending", null],
    ["descending", null],
    ["attach-file", null],
    ["error-outline", null],
    ["roster-design", null],
    ["undo", null]
];

export default icon_list